import type { Metadata } from 'next'
import { Exo_2 } from 'next/font/google'
import 'public/styles/globals.css'
import '@mantine/core/styles.css'
import { MantineProvider } from '@mantine/core'

import React from 'react'

const font = Exo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Test constructor',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ru'>
            <body className={font.className}>
                <MantineProvider defaultColorScheme='dark'>{children}</MantineProvider>
            </body>
        </html>
    )
}
