import type { Metadata } from 'next'
import { Exo_2 } from 'next/font/google'
import 'public/styles/globals.css'
import '@mantine/core/styles.css'
import { MantineProvider } from '@mantine/core'
import '@mantine/notifications/styles.css'
import React from 'react'
import { Notifications } from '@mantine/notifications'
import { Container } from '@mantine/core'
import { Header } from '@/components/layout/header'
import { RedirectToDashboard } from '@/components/ui/redirect-to-dashboard'

const font = Exo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Test constructor',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ru'>
            <body className={font.className}>
                <MantineProvider defaultColorScheme='auto'>
                    <Container fluid pt={20}>
                        <Header />

                        <Notifications />
                        <RedirectToDashboard>{children}</RedirectToDashboard>
                    </Container>
                </MantineProvider>
            </body>
        </html>
    )
}
